dist: trusty
language: java

rust:
  - stable

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      script:
       - export JAVA_HOME="$(/usr/libexec/java_home)"
       - cargo clean --manifest-path=rust/Cargo.toml
       - cargo update --manifest-path=rust/Cargo.toml
       - J4RS_CONSOLE_LOG_LEVEL=debug cargo test --manifest-path=rust/Cargo.toml -- --nocapture
    - os: linux
      jdk: openjdk11
      script:
       - mvn -f java/pom.xml clean install
       - cargo clean --manifest-path=rust/Cargo.toml
       - cargo update --manifest-path=rust/Cargo.toml
       - cargo test --manifest-path=rust/Cargo.toml

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source ~/.cargo/env
