dist: trusty
language: java

rust:
  - stable

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      script:
        - echo "-----------TESTS"
        - /usr/libexec/java_home
        - echo "-----------"
        - J4RS_CONSOLE_LOG_LEVEL=debug cargo test --manifest-path=rust/Cargo.toml -- --nocapture
    - os: linux
      jdk: openjdk11
      script:
       - mvn -f java/pom.xml clean install
       - cargo build --manifest-path=rust/Cargo.toml
       - cargo test --manifest-path=rust/Cargo.toml

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source ~/.cargo/env
