# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

image: Visual Studio 2017
environment:
  global:
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - ps: >-
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

build_script:
  - mvn -f java/pom.xml clean install
  - cargo clean --manifest-path=rust/Cargo.toml
  - cargo build --manifest-path=rust/Cargo.toml

test_script:
  # we don't run the "test phase" when doing deploys
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      cargo test --manifest-path=rust/Cargo.toml
    )

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

branches:
  only:
    # Release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  - provider: Email
    on_build_success: false
