# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

image: Visual Studio 2017
environment:
  global:
    JAVA_HOME: C:\Program Files\Java\jdk11

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain stable --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - cargo -V

build_script:
  - mvn -f java/pom.xml clean install
  - cargo clean --manifest-path=rust/Cargo.toml
  - cargo build --manifest-path=rust/Cargo.toml

test_script:
  - J4RS_CONSOLE_LOG_LEVEL=debug cargo test --manifest-path=rust/Cargo.toml  -- --nocapture
